version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Skipping build step for now
  post_build:
    commands:
      - echo Build complete!

artifacts:
  files:
    - '**/*'
